sudo: required
language: php

services:
  - docker

cache:
  directories:
  - vendor

branches:
  only:
  - master
  - develop


before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker pull gerardojunior/tap.api.environment:stable

script:
  - docker run -it --rm -e DEBUG=false -v $(pwd):/usr/share/src gerardojunior/tap.api.environment:stable composer test
  - docker-compose up -d
  - docker-compose down

after_script:
  - docker stop $(docker ps -a -q)
  - docker-compose down